-- registration 테이블이 이미 존재하므로 스키마만 확인
-- 기존 테이블 구조:
-- create table public.registration (
--   대분류 text not null,
--   품목 text not null,
--   품종 text not null,
--   파종 / 육묘 구분 text null,
--   총 재배기간 (파종 ~ 수확) (단위:일) bigint null,
--   육묘기간 (파종 ~ 정식) (단위:일) bigint null,
--   작물번호 bigint generated by default as identity not null,
--   생육 기간 (밭을 사용하는 기간) (단위:일) bigint null,
--   constraint registration_pkey primary key ("작물번호")
-- ) TABLESPACE pg_default;

-- 인덱스도 이미 존재:
-- create index IF not exists "registration_대분류_idx" on public.registration using btree ("대분류") TABLESPACE pg_default;
-- create index IF not exists "registration_품목_idx" on public.registration using btree ("품목") TABLESPACE pg_default;
-- create index IF not exists "registration_품종_idx" on public.registration using btree ("품종") TABLESPACE pg_default;

-- 권한만 확인/설정
GRANT ALL ON public.registration TO authenticated;
